import { Global, ScreenId, Backend } from "../common.slint";
import { ScreenBase } from "../components/screen.slint";
import { FileListView } from "../components/file_list.slint";
import { ControlHint } from "../components/control_hint.slint";

export component RomSelectScreen inherits ScreenBase {
    private property <bool> is-loading: false;
    private property <bool> has-error: Backend.rom-select-error != "";

    title: "Load ROM...";
    forward-focus: list;

    // Hack to call set-current-item when the backend forces a new item.
    private property <int> _selected-index: Backend.rom-select-index;
    changed _selected-index => {
        list.set-current-item(Backend.rom-select-index);
    }

    i-focus-scope := FocusScope {
        key-pressed(event) => {
            if (Backend.rom-select-is-loading) {
                accept
            } else if (has-error) {
                if (event.text == "a" || event.text == "b") {
                    Backend.rom-select-error = "";
                    list.set-current-item(Backend.rom-select-index);
                }
                accept
            } else if event.text == "Home" && !Global.home-consumed {
                Global.set-screen(ScreenId.MainMenu);
                accept
            } else if (event.text == "b" && !event.repeat) {
                Backend.rom-select-up();
                accept
            } else {
                reject
            }
        }
        VerticalLayout {
            height: 100%;
            spacing: 2px;

            Text {
                text: Backend.rom-select-path;
            }

            Rectangle {
                private property <length> scrollbar-width: 2px;
                private property <bool> has-scrollbar: list.viewport-height > list.height;
                border-width: 1px;
                border-color: black;

                list := FileListView {
                    x: 0px;
                    width: scroll-bar.x;
                    model: Backend.rom-select-list;
                    wrap: !Backend.rom-select-scroll;
                    auto-continue: Backend.rom-select-scroll;
                    has-previous: Backend.rom-select-has-previous;
                    has-next: Backend.rom-select-has-next;
                    page-requested(next) => { Backend.rom-select-page(next); }
                    disabled: Backend.rom-select-is-loading || has-error;
                    on-item-selected(i) => {
                        Backend.rom-select-index = i;
                        if Backend.rom-select-selected(i) {
                            Global.set-screen(ScreenId.Game);
                        }
                    }
                    current-item-changed(i) => {
                        Backend.rom-select-focused(i);
                    }
                }

                scroll-bar := Rectangle {
                    visible: has-scrollbar;
                    x: parent.width - self.width - 2px;
                    y: 2px;
                    width: scrollbar-width;
                    height: parent.height - 4px;
                    inner := Rectangle {
                        y: (-list.viewport-y / max(1px, list.viewport-height)) * parent.height;
                        width: 100%;
                        height: (list.height / max(1px, list.viewport-height)) * parent.height;
                        background: black;
                    }
                }
            }

            Text {
                text: Backend.rom-select-scroll ? "Up/Down: scroll" : "Left/Right or L/R: page";
            }

            HorizontalLayout {
                alignment: space-between;

                ControlHint {
                    label: "Home";
                    button: "home";
                }

                ControlHint {
                    label: "Up";
                    button: "b";
                }

                ControlHint {
                    label: "Select";
                    button: "a";
                }
            }
        }
    }

    if Backend.rom-select-is-loading:  Rectangle {
        background: #FFF;
        border-color: black;
        border-width: 1px;
        width: i-layout.min-width;
        height: i-layout.min-height;

        i-layout := VerticalLayout {
            padding: 8px;
            spacing: 4px;
            i-text := Text {
                horizontal-alignment: center;
                text: "Loading...";
            }
        }
    }

    if has-error: Rectangle {
        background: #FFF;
        border-color: black;
        border-width: 1px;
        width: min(self.preferred-width, parent.width - 16px);
        height: min(self.preferred-height, parent.height - 32px);

        i-error-layout := VerticalLayout {
            padding: 8px;
            spacing: 4px;
            Text {
                horizontal-alignment: center;
                text: Backend.rom-select-error;
                overflow: elide;
            }
        }
    }
}
